app:
  name: "oil-supervision-server"
  mode: "prod"
  port: 9090
jwt:
  secret: "oil-supervision-local-secret-2026"
mysql:
  host: "mysql"
  port: 3306
  user: "root"
  password: "oiltrace"
  db: "oil_supervision"
