app:
  name: "oil-supervision-server"
  mode: "dev"
  port: 9090
jwt:
  secret: "oil-supervision-local-secret-2026"
mysql:
  host: "127.0.0.1"
  port: 3337
  user: "root"
  password: "oiltrace"
  db: "oil_supervision"
