import request from '@/utils/request'

export const dashboard = () => request({ url: '/dashboard', method: 'get' })
export const batches = () => request({ url: '/batches', method: 'get' })
export const traceBatches = () => request({ url: '/trace-batches', method: 'get' })
export const createBatch = data => request({ url: '/batches', method: 'post', data })
export const updateBatch = data => request({ url: '/batches', method: 'put', data })
export const deleteBatch = id => request({ url: '/batches', method: 'delete', data: { id }})
export const submitBatch = id => request({ url: '/batches/submit', method: 'post', data: { id }})
export const factoryDecision = data => request({ url: '/factory/decision', method: 'post', data })
export const submitProcessing = data => request({ url: '/factory/processing', method: 'post', data })
export const roleOptions = role => request({ url: '/role-options', method: 'get', params: { role }})
export const createTransport = data => request({ url: '/transport', method: 'post', data })
export const transports = () => request({ url: '/transport', method: 'get' })
export const transportDecision = data => request({ url: '/transport/decision', method: 'post', data })
export const startTransport = id => request({ url: '/transport/start', method: 'post', data: { id }})
export const generateNodes = (id, count = 8) => request({ url: '/transport/nodes', method: 'post', data: { id, count }})
export const completeTransport = id => request({ url: '/transport/complete', method: 'post', data: { id }})
export const retailDecision = data => request({ url: '/retail/decision', method: 'post', data })
export const addCorrection = data => request({ url: '/corrections', method: 'post', data })
export const traceDetail = code => request({ url: `/trace/${code}`, method: 'get' })
export const evidence = () => request({ url: '/evidence', method: 'get' })
export const nodes = id => request({ url: `/transport/${id}/nodes`, method: 'get' })

// Fabric 存证管理接口
export const verifyEvidence = id => request({ url: `/evidence/verify/${id}`, method: 'get' })
export const retryEvidence = id => request({ url: '/evidence/retry', method: 'post', data: { id }})
export const queryChainEvent = eventId => request({ url: `/evidence/chain/${eventId}`, method: 'get' })
export const fabricStatus = () => request({ url: '/fabric/status', method: 'get' })
